version: '3.9'
services:
  postgres:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=mario
      - POSTGRES_PASSWORD=mario123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '9876:5432'
volumes:
  postgres:
