export const ENROLLED_COURSES_LIST_REQUEST = 'ENROLLED_COURSES_LIST_REQUEST'
export const ENROLLED_COURSES_LIST_SUCCESS = 'ENROLLED_COURSES_LIST_SUCCESS'
export const ENROLLED_COURSES_LIST_FAIL = 'ENROLLED_COURSES_LIST_FAIL'

export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS'
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL'

export const ENROLL_TO_COURSE_REQUEST = 'ENROLL_TO_COURSE_REQUEST'
export const ENROLL_TO_COURSE_SUCCESS = 'ENROLL_TO_COURSE_SUCCESS'
export const ENROLL_TO_COURSE_FAIL = 'ENROLL_TO_COURSE_FAIL'
export const ENROLL_TO_COURSE_RESET = 'ENROLL_TO_COURSE_RESET'
