export const EXERCISE_DETAILS_REQUEST = 'EXERCISE_DETAILS_REQUEST'
export const EXERCISE_DETAILS_SUCCESS = 'EXERCISE_DETAILS_SUCCESS'
export const EXERCISE_DETAILS_FAIL = 'EXERCISE_DETAILS_FAIL'
export const EXERCISE_DETAILS_RESET = 'EXERCISE_DETAILS_RESET'
