export const GLOBAL_NEWS_REQUEST = 'GLOBAL_NEWS_REQUEST'
export const GLOBAL_NEWS_SUCCESS = 'GLOBAL_NEWS_SUCCESS'
export const GLOBAL_NEWS_FAIL = 'GLOBAL_NEWS_FAIL'

export const GLOBAL_NEWS_CREATE_REQUEST = 'GLOBAL_NEWS_CREATE_REQUEST'
export const GLOBAL_NEWS_CREATE_SUCCESS = 'GLOBAL_NEWS_CREATE_SUCCESS'
export const GLOBAL_NEWS_CREATE_FAIL = 'GLOBAL_NEWS_CREATE_FAIL'
export const GLOBAL_NEWS_CREATE_RESET = 'GLOBAL_NEWS_CREATE_RESET'

export const GLOBAL_NEWS_UPDATE_REQUEST = 'GLOBAL_NEWS_UPDATE_REQUEST'
export const GLOBAL_NEWS_UPDATE_SUCCESS = 'GLOBAL_NEWS_UPDATE_SUCCESS'
export const GLOBAL_NEWS_UPDATE_FAIL = 'GLOBAL_NEWS_UPDATE_FAIL'
export const GLOBAL_NEWS_UPDATE_RESET = 'GLOBAL_NEWS_UPDATE_RESET'

export const GLOBAL_NEWS_DELETE_REQUEST = 'GLOBAL_NEWS_DELETE_REQUEST'
export const GLOBAL_NEWS_DELETE_SUCCESS = 'GLOBAL_NEWS_DELETE_SUCCESS'
export const GLOBAL_NEWS_DELETE_FAIL = 'GLOBAL_NEWS_DELETE_FAIL'
export const GLOBAL_NEWS_DELETE_RESET = 'GLOBAL_NEWS_DELETE_RESET'
